name: publish_docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git config user.name docs-bot
      - run: git config user.email docs-bot@yolo.io
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material 'mkdocstrings[python]' mike
      - run: mkdocs gh-deploy --force
