name: PR Plan
on: [pull_request]
permissions:
  contents: read
  pull-requests: write

jobs:
    terraform:
        name: 'Terraform Plan for PR'
        runs-on: ubuntu-latest
        environment: dev

        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: terraform plan
              uses: dflook/terraform-plan@v1
              with:
                path: terraform
                var_file: |
                  terraform/variables/common.tfvars
                  terraform/variables/dev.tfvars
                backend_config_file: terraform/conf/dev.backend.conf
              env:
                GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
